#!/bin/bash

# create patch
# diff -u rel/funnel/lib/entop-0.0.1/ebin/entop.app deps/entop/ebin/entop.app > entop.patch
# diff -u rel/funnel/lib/cecho-0.0.3/ebin/cecho.app deps/cecho/ebin/cecho.app > cecho.patch

set -e

echo Cleanup
rm -rf rel/funnel rel/funnel_mini* rel/*.tar.gz

SUS_ARCH_USER=${1}
SUS_ARCH_PASS=${2}
FROM_VSN=${3}
TO_VSN=${4}

TAR_TMP_BASE=/tmp/
TAR_URL_BASE=http://sus.dev1team.net/sus/poweralley/
PRJ_NAME=funnel_mini
TAR_NAME_BASE=centos6.x86_64.tar.gz

echo Generate upgrade from ${FROM_VSN} to ${TO_VSN}

function download {
    PRJ_NAME_W_VER=${PRJ_NAME}-${1}
    TAR_NAME=${PRJ_NAME_W_VER}-${TAR_NAME_BASE}
    TAR_URL=${TAR_URL_BASE}${TAR_NAME}
    TAR_TMP=${TAR_TMP_BASE}${TAR_NAME}
    wget --http-user=${SUS_ARCH_USER} --http-password=${SUS_ARCH_PASS} -O ${TAR_TMP} ${TAR_URL}

    tar xzf ${TAR_TMP} -C rel/

    patch rel/${PRJ_NAME_W_VER}/lib/entop-0.0.1/ebin/entop.app entop.patch
    patch rel/${PRJ_NAME_W_VER}/lib/cecho-0.0.3/ebin/cecho.app cecho.patch


    ln -s funnel.rel rel/${PRJ_NAME_W_VER}/releases/${1}/funnel-${1}.rel
    ln -s funnel.boot rel/${PRJ_NAME_W_VER}/releases/${1}/funnel-${1}.boot
    ln -s funnel.boot rel/${PRJ_NAME_W_VER}/releases/${1}/start.boot
}

download ${FROM_VSN}
download ${TO_VSN}

UPGRADE_TO=rel/funnel_mini-${TO_VSN}/releases/${TO_VSN}/funnel-${TO_VSN}
UPGRADE_TO_EBIN_PATH=rel/funnel_mini-${TO_VSN}/lib/*/ebin
UPGRADE_TO_RELEASE_PATH=rel/funnel_mini-${TO_VSN}/releases/${TO_VSN}/
UPGRADE_FROM=rel/funnel_mini-${FROM_VSN}/releases/${FROM_VSN}/funnel-${FROM_VSN}
DOWNGRADE_TO=${UPGRADE_FROM}
UPGRADE_FROM_EBIN_PATH=rel/funnel_mini-${FROM_VSN}/lib/*/ebin

erl -eval "systools:make_relup(\"${UPGRADE_TO}\", [\"${UPGRADE_FROM}\"], [\"${DOWNGRADE_TO}\"], [{path, [\"${UPGRADE_TO_EBIN_PATH}\", \"${UPGRADE_FROM_EBIN_PATH}\"]}, {outdir, \"${UPGRADE_TO_RELEASE_PATH}\"}])." -s init stop -noshell

erl -eval "systools:make_tar(\"${UPGRADE_TO}\", [{path, [\"${UPGRADE_TO_EBIN_PATH}\"]}, {outdir, \"rel/\"},{dirs,[include]}])." -s init stop -noshell

